//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppResources.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResShared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResShared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppResources.Localization.Resources.ResShared", typeof(ResShared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Btn_Accept {
            get {
                return ResourceManager.GetString("Btn_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string Btn_AddItem {
            get {
                return ResourceManager.GetString("Btn_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Btn_Apply {
            get {
                return ResourceManager.GetString("Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Btn_Approve {
            get {
                return ResourceManager.GetString("Btn_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Btn_Choose {
            get {
                return ResourceManager.GetString("Btn_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Btn_Clear {
            get {
                return ResourceManager.GetString("Btn_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Btn_Collapse {
            get {
                return ResourceManager.GetString("Btn_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Btn_Confirm {
            get {
                return ResourceManager.GetString("Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Btn_Download {
            get {
                return ResourceManager.GetString("Btn_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string Btn_Expand {
            get {
                return ResourceManager.GetString("Btn_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Btn_Export {
            get {
                return ResourceManager.GetString("Btn_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Btn_Filter {
            get {
                return ResourceManager.GetString("Btn_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Btn_Finish {
            get {
                return ResourceManager.GetString("Btn_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Btn_Hide {
            get {
                return ResourceManager.GetString("Btn_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Btn_Import {
            get {
                return ResourceManager.GetString("Btn_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Btn_Next {
            get {
                return ResourceManager.GetString("Btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Btn_Prev {
            get {
                return ResourceManager.GetString("Btn_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Btn_Preview {
            get {
                return ResourceManager.GetString("Btn_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Btn_Print {
            get {
                return ResourceManager.GetString("Btn_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Btn_Refresh {
            get {
                return ResourceManager.GetString("Btn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Btn_Reject {
            get {
                return ResourceManager.GetString("Btn_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Btn_Reset {
            get {
                return ResourceManager.GetString("Btn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Btn_SaveChanges {
            get {
                return ResourceManager.GetString("Btn_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        public static string Btn_SaveCont {
            get {
                return ResourceManager.GetString("Btn_SaveCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Btn_Select {
            get {
                return ResourceManager.GetString("Btn_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Btn_Show {
            get {
                return ResourceManager.GetString("Btn_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Btn_Submit {
            get {
                return ResourceManager.GetString("Btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Btn_Update {
            get {
                return ResourceManager.GetString("Btn_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Btn_Upload {
            get {
                return ResourceManager.GetString("Btn_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Btn_View {
            get {
                return ResourceManager.GetString("Btn_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string Btn_ViewAll {
            get {
                return ResourceManager.GetString("Btn_ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Fld_ConfirmPass {
            get {
                return ResourceManager.GetString("Fld_ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        public static string Fld_EnterEmail {
            get {
                return ResourceManager.GetString("Fld_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        public static string Fld_EnterName {
            get {
                return ResourceManager.GetString("Fld_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string Fld_EnterPass {
            get {
                return ResourceManager.GetString("Fld_EnterPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number.
        /// </summary>
        public static string Fld_EnterPhone {
            get {
                return ResourceManager.GetString("Fld_EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Fld_Search {
            get {
                return ResourceManager.GetString("Fld_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Lbl_Address {
            get {
                return ResourceManager.GetString("Lbl_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Lbl_Category {
            get {
                return ResourceManager.GetString("Lbl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Lbl_City {
            get {
                return ResourceManager.GetString("Lbl_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Lbl_Code {
            get {
                return ResourceManager.GetString("Lbl_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Lbl_ConfirmPass {
            get {
                return ResourceManager.GetString("Lbl_ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Lbl_Country {
            get {
                return ResourceManager.GetString("Lbl_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string Lbl_CreatedAt {
            get {
                return ResourceManager.GetString("Lbl_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string Lbl_CreatedBy {
            get {
                return ResourceManager.GetString("Lbl_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Lbl_Date {
            get {
                return ResourceManager.GetString("Lbl_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Lbl_Description {
            get {
                return ResourceManager.GetString("Lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Lbl_Email {
            get {
                return ResourceManager.GetString("Lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Lbl_File {
            get {
                return ResourceManager.GetString("Lbl_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Lbl_FirstName {
            get {
                return ResourceManager.GetString("Lbl_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Lbl_FullName {
            get {
                return ResourceManager.GetString("Lbl_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Lbl_ID {
            get {
                return ResourceManager.GetString("Lbl_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Lbl_Image {
            get {
                return ResourceManager.GetString("Lbl_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Lbl_LastName {
            get {
                return ResourceManager.GetString("Lbl_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Lbl_Mobile {
            get {
                return ResourceManager.GetString("Lbl_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Lbl_Name {
            get {
                return ResourceManager.GetString("Lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Lbl_Notes {
            get {
                return ResourceManager.GetString("Lbl_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Lbl_Password {
            get {
                return ResourceManager.GetString("Lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Lbl_Phone {
            get {
                return ResourceManager.GetString("Lbl_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Lbl_Price {
            get {
                return ResourceManager.GetString("Lbl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Lbl_Quantity {
            get {
                return ResourceManager.GetString("Lbl_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Lbl_Role {
            get {
                return ResourceManager.GetString("Lbl_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Lbl_Status {
            get {
                return ResourceManager.GetString("Lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Lbl_Total {
            get {
                return ResourceManager.GetString("Lbl_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Lbl_Type {
            get {
                return ResourceManager.GetString("Lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated At.
        /// </summary>
        public static string Lbl_UpdatedAt {
            get {
                return ResourceManager.GetString("Lbl_UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        public static string Lbl_UpdatedBy {
            get {
                return ResourceManager.GetString("Lbl_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Lbl_ZipCode {
            get {
                return ResourceManager.GetString("Lbl_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Menu_Login {
            get {
                return ResourceManager.GetString("Menu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Menu_Orders {
            get {
                return ResourceManager.GetString("Menu_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Menu_Products {
            get {
                return ResourceManager.GetString("Menu_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Menu_Profile {
            get {
                return ResourceManager.GetString("Menu_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Menu_Register {
            get {
                return ResourceManager.GetString("Menu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Menu_Reports {
            get {
                return ResourceManager.GetString("Menu_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Menu_Users {
            get {
                return ResourceManager.GetString("Menu_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Msg_AllItems {
            get {
                return ResourceManager.GetString("Msg_AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string Msg_ConfirmDelete {
            get {
                return ResourceManager.GetString("Msg_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save changes?.
        /// </summary>
        public static string Msg_ConfirmSave {
            get {
                return ResourceManager.GetString("Msg_ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Msg_Info {
            get {
                return ResourceManager.GetString("Msg_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Msg_Loading {
            get {
                return ResourceManager.GetString("Msg_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string Msg_NoData {
            get {
                return ResourceManager.GetString("Msg_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Msg_Optional {
            get {
                return ResourceManager.GetString("Msg_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Msg_Processing {
            get {
                return ResourceManager.GetString("Msg_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Msg_Required {
            get {
                return ResourceManager.GetString("Msg_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select --.
        /// </summary>
        public static string Msg_SelectItem {
            get {
                return ResourceManager.GetString("Msg_SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully.
        /// </summary>
        public static string Msg_Success {
            get {
                return ResourceManager.GetString("Msg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Msg_Warning {
            get {
                return ResourceManager.GetString("Msg_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Opt_Active {
            get {
                return ResourceManager.GetString("Opt_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Opt_Disabled {
            get {
                return ResourceManager.GetString("Opt_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Opt_Enabled {
            get {
                return ResourceManager.GetString("Opt_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Opt_Female {
            get {
                return ResourceManager.GetString("Opt_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Opt_Inactive {
            get {
                return ResourceManager.GetString("Opt_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Opt_Male {
            get {
                return ResourceManager.GetString("Opt_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Opt_No {
            get {
                return ResourceManager.GetString("Opt_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Opt_Ok {
            get {
                return ResourceManager.GetString("Opt_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Opt_Yes {
            get {
                return ResourceManager.GetString("Opt_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string Page_About {
            get {
                return ResourceManager.GetString("Page_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Page_Account {
            get {
                return ResourceManager.GetString("Page_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Page_Admin {
            get {
                return ResourceManager.GetString("Page_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Page_Contact {
            get {
                return ResourceManager.GetString("Page_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Page_Customers {
            get {
                return ResourceManager.GetString("Page_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Page_Dashboard {
            get {
                return ResourceManager.GetString("Page_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Page_Help {
            get {
                return ResourceManager.GetString("Page_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Page_Home {
            get {
                return ResourceManager.GetString("Page_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Page_Orders {
            get {
                return ResourceManager.GetString("Page_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Page_Privacy {
            get {
                return ResourceManager.GetString("Page_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Page_Products {
            get {
                return ResourceManager.GetString("Page_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Page_Profile {
            get {
                return ResourceManager.GetString("Page_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Page_Reports {
            get {
                return ResourceManager.GetString("Page_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Page_Settings {
            get {
                return ResourceManager.GetString("Page_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Page_Suppliers {
            get {
                return ResourceManager.GetString("Page_Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Page_Support {
            get {
                return ResourceManager.GetString("Page_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string Page_Terms {
            get {
                return ResourceManager.GetString("Page_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Page_Users {
            get {
                return ResourceManager.GetString("Page_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Information.
        /// </summary>
        public static string Sec_AddressInfo {
            get {
                return ResourceManager.GetString("Sec_AddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string Sec_ContactInfo {
            get {
                return ResourceManager.GetString("Sec_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Information.
        /// </summary>
        public static string Sec_LoginInfo {
            get {
                return ResourceManager.GetString("Sec_LoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        public static string Sec_OrderSummary {
            get {
                return ResourceManager.GetString("Sec_OrderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information.
        /// </summary>
        public static string Sec_PaymentInfo {
            get {
                return ResourceManager.GetString("Sec_PaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string Sec_PersonalInfo {
            get {
                return ResourceManager.GetString("Sec_PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Information.
        /// </summary>
        public static string Sec_ShippingInfo {
            get {
                return ResourceManager.GetString("Sec_ShippingInfo", resourceCulture);
            }
        }
    }
}
