//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppResources.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResUserModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResUserModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppResources.Localization.Resources.ResUserModel", typeof(ResUserModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Btn_Accept {
            get {
                return ResourceManager.GetString("Btn_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string Btn_AddItem {
            get {
                return ResourceManager.GetString("Btn_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Btn_Apply {
            get {
                return ResourceManager.GetString("Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Btn_Approve {
            get {
                return ResourceManager.GetString("Btn_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Btn_Choose {
            get {
                return ResourceManager.GetString("Btn_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Btn_Clear {
            get {
                return ResourceManager.GetString("Btn_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Btn_Collapse {
            get {
                return ResourceManager.GetString("Btn_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Btn_Confirm {
            get {
                return ResourceManager.GetString("Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Btn_Continue {
            get {
                return ResourceManager.GetString("Btn_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Btn_Decline {
            get {
                return ResourceManager.GetString("Btn_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Btn_Download {
            get {
                return ResourceManager.GetString("Btn_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string Btn_Expand {
            get {
                return ResourceManager.GetString("Btn_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Btn_Export {
            get {
                return ResourceManager.GetString("Btn_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Btn_Filter {
            get {
                return ResourceManager.GetString("Btn_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Btn_Finish {
            get {
                return ResourceManager.GetString("Btn_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Btn_Forward {
            get {
                return ResourceManager.GetString("Btn_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string Btn_GoBack {
            get {
                return ResourceManager.GetString("Btn_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Btn_Hide {
            get {
                return ResourceManager.GetString("Btn_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Btn_Import {
            get {
                return ResourceManager.GetString("Btn_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string Btn_LearnMore {
            get {
                return ResourceManager.GetString("Btn_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Btn_Next {
            get {
                return ResourceManager.GetString("Btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Btn_Prev {
            get {
                return ResourceManager.GetString("Btn_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Btn_Preview {
            get {
                return ResourceManager.GetString("Btn_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Btn_Print {
            get {
                return ResourceManager.GetString("Btn_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string Btn_ReadMore {
            get {
                return ResourceManager.GetString("Btn_ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Btn_Refresh {
            get {
                return ResourceManager.GetString("Btn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Btn_Reject {
            get {
                return ResourceManager.GetString("Btn_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Btn_Reply {
            get {
                return ResourceManager.GetString("Btn_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Btn_Reset {
            get {
                return ResourceManager.GetString("Btn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Btn_SaveChanges {
            get {
                return ResourceManager.GetString("Btn_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        public static string Btn_SaveCont {
            get {
                return ResourceManager.GetString("Btn_SaveCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Btn_Select {
            get {
                return ResourceManager.GetString("Btn_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Btn_Send {
            get {
                return ResourceManager.GetString("Btn_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Btn_Show {
            get {
                return ResourceManager.GetString("Btn_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Btn_Submit {
            get {
                return ResourceManager.GetString("Btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Btn_Subscribe {
            get {
                return ResourceManager.GetString("Btn_Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string Btn_TryAgain {
            get {
                return ResourceManager.GetString("Btn_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Btn_Update {
            get {
                return ResourceManager.GetString("Btn_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Btn_Upload {
            get {
                return ResourceManager.GetString("Btn_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Btn_View {
            get {
                return ResourceManager.GetString("Btn_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string Btn_ViewAll {
            get {
                return ResourceManager.GetString("Btn_ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file.
        /// </summary>
        public static string Fld_ChooseFile {
            get {
                return ResourceManager.GetString("Fld_ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Fld_ConfirmPass {
            get {
                return ResourceManager.GetString("Fld_ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string Fld_EndDate {
            get {
                return ResourceManager.GetString("Fld_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address.
        /// </summary>
        public static string Fld_EnterAddress {
            get {
                return ResourceManager.GetString("Fld_EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter barcode.
        /// </summary>
        public static string Fld_EnterBarcode {
            get {
                return ResourceManager.GetString("Fld_EnterBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter city.
        /// </summary>
        public static string Fld_EnterCity {
            get {
                return ResourceManager.GetString("Fld_EnterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code.
        /// </summary>
        public static string Fld_EnterCode {
            get {
                return ResourceManager.GetString("Fld_EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter country.
        /// </summary>
        public static string Fld_EnterCountry {
            get {
                return ResourceManager.GetString("Fld_EnterCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        public static string Fld_EnterDescription {
            get {
                return ResourceManager.GetString("Fld_EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        public static string Fld_EnterEmail {
            get {
                return ResourceManager.GetString("Fld_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        public static string Fld_EnterName {
            get {
                return ResourceManager.GetString("Fld_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter notes.
        /// </summary>
        public static string Fld_EnterNotes {
            get {
                return ResourceManager.GetString("Fld_EnterNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string Fld_EnterPass {
            get {
                return ResourceManager.GetString("Fld_EnterPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number.
        /// </summary>
        public static string Fld_EnterPhone {
            get {
                return ResourceManager.GetString("Fld_EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter price.
        /// </summary>
        public static string Fld_EnterPrice {
            get {
                return ResourceManager.GetString("Fld_EnterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter quantity.
        /// </summary>
        public static string Fld_EnterQuantity {
            get {
                return ResourceManager.GetString("Fld_EnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter SKU.
        /// </summary>
        public static string Fld_EnterSKU {
            get {
                return ResourceManager.GetString("Fld_EnterSKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter postal code.
        /// </summary>
        public static string Fld_EnterZip {
            get {
                return ResourceManager.GetString("Fld_EnterZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Fld_From {
            get {
                return ResourceManager.GetString("Fld_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Fld_Max {
            get {
                return ResourceManager.GetString("Fld_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Fld_Min {
            get {
                return ResourceManager.GetString("Fld_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file chosen.
        /// </summary>
        public static string Fld_NoFileChosen {
            get {
                return ResourceManager.GetString("Fld_NoFileChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Fld_Search {
            get {
                return ResourceManager.GetString("Fld_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date.
        /// </summary>
        public static string Fld_SelectDate {
            get {
                return ResourceManager.GetString("Fld_SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select time.
        /// </summary>
        public static string Fld_SelectTime {
            get {
                return ResourceManager.GetString("Fld_SelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Fld_StartDate {
            get {
                return ResourceManager.GetString("Fld_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Fld_To {
            get {
                return ResourceManager.GetString("Fld_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here....
        /// </summary>
        public static string Fld_TypeHere {
            get {
                return ResourceManager.GetString("Fld_TypeHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Lbl_Address {
            get {
                return ResourceManager.GetString("Lbl_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Lbl_Attachment {
            get {
                return ResourceManager.GetString("Lbl_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string Lbl_Barcode {
            get {
                return ResourceManager.GetString("Lbl_Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Lbl_Brand {
            get {
                return ResourceManager.GetString("Lbl_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Lbl_Category {
            get {
                return ResourceManager.GetString("Lbl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Lbl_City {
            get {
                return ResourceManager.GetString("Lbl_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Lbl_Code {
            get {
                return ResourceManager.GetString("Lbl_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Lbl_Color {
            get {
                return ResourceManager.GetString("Lbl_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Lbl_Comments {
            get {
                return ResourceManager.GetString("Lbl_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Lbl_ConfirmPass {
            get {
                return ResourceManager.GetString("Lbl_ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Lbl_Country {
            get {
                return ResourceManager.GetString("Lbl_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string Lbl_CreatedAt {
            get {
                return ResourceManager.GetString("Lbl_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string Lbl_CreatedBy {
            get {
                return ResourceManager.GetString("Lbl_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string Lbl_CurrentPass {
            get {
                return ResourceManager.GetString("Lbl_CurrentPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Lbl_Date {
            get {
                return ResourceManager.GetString("Lbl_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Lbl_Description {
            get {
                return ResourceManager.GetString("Lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string Lbl_Dimensions {
            get {
                return ResourceManager.GetString("Lbl_Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Lbl_Discount {
            get {
                return ResourceManager.GetString("Lbl_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Lbl_Downloads {
            get {
                return ResourceManager.GetString("Lbl_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Lbl_Email {
            get {
                return ResourceManager.GetString("Lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Lbl_File {
            get {
                return ResourceManager.GetString("Lbl_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Lbl_FirstName {
            get {
                return ResourceManager.GetString("Lbl_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Lbl_FullName {
            get {
                return ResourceManager.GetString("Lbl_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Lbl_ID {
            get {
                return ResourceManager.GetString("Lbl_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Lbl_Image {
            get {
                return ResourceManager.GetString("Lbl_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Lbl_LastName {
            get {
                return ResourceManager.GetString("Lbl_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string Lbl_Likes {
            get {
                return ResourceManager.GetString("Lbl_Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Lbl_Mobile {
            get {
                return ResourceManager.GetString("Lbl_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Lbl_Name {
            get {
                return ResourceManager.GetString("Lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Lbl_NewPass {
            get {
                return ResourceManager.GetString("Lbl_NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Lbl_Notes {
            get {
                return ResourceManager.GetString("Lbl_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Lbl_Password {
            get {
                return ResourceManager.GetString("Lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Lbl_Permissions {
            get {
                return ResourceManager.GetString("Lbl_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Lbl_Phone {
            get {
                return ResourceManager.GetString("Lbl_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Lbl_Price {
            get {
                return ResourceManager.GetString("Lbl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Lbl_Quantity {
            get {
                return ResourceManager.GetString("Lbl_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Lbl_Rating {
            get {
                return ResourceManager.GetString("Lbl_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Lbl_Reviews {
            get {
                return ResourceManager.GetString("Lbl_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Lbl_Role {
            get {
                return ResourceManager.GetString("Lbl_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string Lbl_Shipping {
            get {
                return ResourceManager.GetString("Lbl_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Lbl_Size {
            get {
                return ResourceManager.GetString("Lbl_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        public static string Lbl_SKU {
            get {
                return ResourceManager.GetString("Lbl_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State / Province.
        /// </summary>
        public static string Lbl_State {
            get {
                return ResourceManager.GetString("Lbl_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Lbl_Status {
            get {
                return ResourceManager.GetString("Lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Lbl_Subtotal {
            get {
                return ResourceManager.GetString("Lbl_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Lbl_Tax {
            get {
                return ResourceManager.GetString("Lbl_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Lbl_Total {
            get {
                return ResourceManager.GetString("Lbl_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Lbl_Type {
            get {
                return ResourceManager.GetString("Lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated At.
        /// </summary>
        public static string Lbl_UpdatedAt {
            get {
                return ResourceManager.GetString("Lbl_UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        public static string Lbl_UpdatedBy {
            get {
                return ResourceManager.GetString("Lbl_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string Lbl_Views {
            get {
                return ResourceManager.GetString("Lbl_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Lbl_Weight {
            get {
                return ResourceManager.GetString("Lbl_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Lbl_ZipCode {
            get {
                return ResourceManager.GetString("Lbl_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Menu_Account {
            get {
                return ResourceManager.GetString("Menu_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Menu_Admin {
            get {
                return ResourceManager.GetString("Menu_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Menu_Blog {
            get {
                return ResourceManager.GetString("Menu_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Menu_Cart {
            get {
                return ResourceManager.GetString("Menu_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Menu_Checkout {
            get {
                return ResourceManager.GetString("Menu_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Menu_Compare {
            get {
                return ResourceManager.GetString("Menu_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Menu_Customers {
            get {
                return ResourceManager.GetString("Menu_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Menu_Dashboard {
            get {
                return ResourceManager.GetString("Menu_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Menu_Events {
            get {
                return ResourceManager.GetString("Menu_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string Menu_FAQ {
            get {
                return ResourceManager.GetString("Menu_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Menu_Gallery {
            get {
                return ResourceManager.GetString("Menu_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Menu_Login {
            get {
                return ResourceManager.GetString("Menu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Menu_News {
            get {
                return ResourceManager.GetString("Menu_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Offers.
        /// </summary>
        public static string Menu_Offers {
            get {
                return ResourceManager.GetString("Menu_Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Menu_Orders {
            get {
                return ResourceManager.GetString("Menu_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Menu_Products {
            get {
                return ResourceManager.GetString("Menu_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Menu_Profile {
            get {
                return ResourceManager.GetString("Menu_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        public static string Menu_Promotions {
            get {
                return ResourceManager.GetString("Menu_Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Menu_Register {
            get {
                return ResourceManager.GetString("Menu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Menu_Reports {
            get {
                return ResourceManager.GetString("Menu_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Menu_Suppliers {
            get {
                return ResourceManager.GetString("Menu_Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Menu_Support {
            get {
                return ResourceManager.GetString("Menu_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Menu_Users {
            get {
                return ResourceManager.GetString("Menu_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist.
        /// </summary>
        public static string Menu_Wishlist {
            get {
                return ResourceManager.GetString("Menu_Wishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. You don&apos;t have permission to view this page..
        /// </summary>
        public static string Msg_AccessDenied {
            get {
                return ResourceManager.GetString("Msg_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Msg_AllItems {
            get {
                return ResourceManager.GetString("Msg_AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved successfully.
        /// </summary>
        public static string Msg_ChangesSaved {
            get {
                return ResourceManager.GetString("Msg_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel? Unsaved changes will be lost..
        /// </summary>
        public static string Msg_ConfirmCancel {
            get {
                return ResourceManager.GetString("Msg_ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string Msg_ConfirmDelete {
            get {
                return ResourceManager.GetString("Msg_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        public static string Msg_ConfirmLogout {
            get {
                return ResourceManager.GetString("Msg_ConfirmLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save changes?.
        /// </summary>
        public static string Msg_ConfirmSave {
            get {
                return ResourceManager.GetString("Msg_ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        public static string Msg_Deleting {
            get {
                return ResourceManager.GetString("Msg_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string Msg_Downloading {
            get {
                return ResourceManager.GetString("Msg_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Msg_Expired {
            get {
                return ResourceManager.GetString("Msg_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Msg_Info {
            get {
                return ResourceManager.GetString("Msg_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string Msg_InvalidRequest {
            get {
                return ResourceManager.GetString("Msg_InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item added successfully.
        /// </summary>
        public static string Msg_ItemAdded {
            get {
                return ResourceManager.GetString("Msg_ItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item deleted successfully.
        /// </summary>
        public static string Msg_ItemDeleted {
            get {
                return ResourceManager.GetString("Msg_ItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item updated successfully.
        /// </summary>
        public static string Msg_ItemUpdated {
            get {
                return ResourceManager.GetString("Msg_ItemUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Msg_Loading {
            get {
                return ResourceManager.GetString("Msg_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Msg_New {
            get {
                return ResourceManager.GetString("Msg_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string Msg_NoData {
            get {
                return ResourceManager.GetString("Msg_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Msg_None {
            get {
                return ResourceManager.GetString("Msg_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found.
        /// </summary>
        public static string Msg_NotFound {
            get {
                return ResourceManager.GetString("Msg_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed. Please try again..
        /// </summary>
        public static string Msg_OperationFailed {
            get {
                return ResourceManager.GetString("Msg_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Msg_Optional {
            get {
                return ResourceManager.GetString("Msg_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Msg_Processing {
            get {
                return ResourceManager.GetString("Msg_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Msg_Required {
            get {
                return ResourceManager.GetString("Msg_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Msg_Saving {
            get {
                return ResourceManager.GetString("Msg_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select --.
        /// </summary>
        public static string Msg_SelectItem {
            get {
                return ResourceManager.GetString("Msg_SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please login again..
        /// </summary>
        public static string Msg_SessionExpired {
            get {
                return ResourceManager.GetString("Msg_SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully.
        /// </summary>
        public static string Msg_Success {
            get {
                return ResourceManager.GetString("Msg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Msg_Updated {
            get {
                return ResourceManager.GetString("Msg_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string Msg_Uploading {
            get {
                return ResourceManager.GetString("Msg_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Msg_Warning {
            get {
                return ResourceManager.GetString("Msg_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Opt_Active {
            get {
                return ResourceManager.GetString("Opt_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string Opt_Allow {
            get {
                return ResourceManager.GetString("Opt_Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Opt_Approved {
            get {
                return ResourceManager.GetString("Opt_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Opt_Cancelled {
            get {
                return ResourceManager.GetString("Opt_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Opt_Completed {
            get {
                return ResourceManager.GetString("Opt_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string Opt_Delivered {
            get {
                return ResourceManager.GetString("Opt_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string Opt_Deny {
            get {
                return ResourceManager.GetString("Opt_Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Opt_Disabled {
            get {
                return ResourceManager.GetString("Opt_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Opt_Enabled {
            get {
                return ResourceManager.GetString("Opt_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string Opt_Exclude {
            get {
                return ResourceManager.GetString("Opt_Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string Opt_False {
            get {
                return ResourceManager.GetString("Opt_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        public static string Opt_Featured {
            get {
                return ResourceManager.GetString("Opt_Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Opt_Female {
            get {
                return ResourceManager.GetString("Opt_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Opt_Hide {
            get {
                return ResourceManager.GetString("Opt_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Opt_Inactive {
            get {
                return ResourceManager.GetString("Opt_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        public static string Opt_Include {
            get {
                return ResourceManager.GetString("Opt_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string Opt_InProgress {
            get {
                return ResourceManager.GetString("Opt_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Opt_Locked {
            get {
                return ResourceManager.GetString("Opt_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Opt_Male {
            get {
                return ResourceManager.GetString("Opt_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Opt_No {
            get {
                return ResourceManager.GetString("Opt_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Featured.
        /// </summary>
        public static string Opt_NotFeatured {
            get {
                return ResourceManager.GetString("Opt_NotFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Opt_Off {
            get {
                return ResourceManager.GetString("Opt_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Opt_Ok {
            get {
                return ResourceManager.GetString("Opt_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string Opt_On {
            get {
                return ResourceManager.GetString("Opt_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Opt_Other {
            get {
                return ResourceManager.GetString("Opt_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Opt_Paid {
            get {
                return ResourceManager.GetString("Opt_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Opt_Pending {
            get {
                return ResourceManager.GetString("Opt_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Opt_Published {
            get {
                return ResourceManager.GetString("Opt_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refunded.
        /// </summary>
        public static string Opt_Refunded {
            get {
                return ResourceManager.GetString("Opt_Refunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Opt_Rejected {
            get {
                return ResourceManager.GetString("Opt_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned.
        /// </summary>
        public static string Opt_Returned {
            get {
                return ResourceManager.GetString("Opt_Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        public static string Opt_Shipped {
            get {
                return ResourceManager.GetString("Opt_Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Opt_Show {
            get {
                return ResourceManager.GetString("Opt_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string Opt_True {
            get {
                return ResourceManager.GetString("Opt_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.
        /// </summary>
        public static string Opt_Unlocked {
            get {
                return ResourceManager.GetString("Opt_Unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        public static string Opt_Unpaid {
            get {
                return ResourceManager.GetString("Opt_Unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublished.
        /// </summary>
        public static string Opt_Unpublished {
            get {
                return ResourceManager.GetString("Opt_Unpublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unverified.
        /// </summary>
        public static string Opt_Unverified {
            get {
                return ResourceManager.GetString("Opt_Unverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string Opt_Verified {
            get {
                return ResourceManager.GetString("Opt_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Opt_Yes {
            get {
                return ResourceManager.GetString("Opt_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string Page_About {
            get {
                return ResourceManager.GetString("Page_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Page_Account {
            get {
                return ResourceManager.GetString("Page_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Page_Admin {
            get {
                return ResourceManager.GetString("Page_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        public static string Page_Cart {
            get {
                return ResourceManager.GetString("Page_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Page_Checkout {
            get {
                return ResourceManager.GetString("Page_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Products.
        /// </summary>
        public static string Page_Compare {
            get {
                return ResourceManager.GetString("Page_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Page_Contact {
            get {
                return ResourceManager.GetString("Page_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Page_Customers {
            get {
                return ResourceManager.GetString("Page_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Page_Dashboard {
            get {
                return ResourceManager.GetString("Page_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Page_ForgotPassword {
            get {
                return ResourceManager.GetString("Page_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Page_Help {
            get {
                return ResourceManager.GetString("Page_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Page_Home {
            get {
                return ResourceManager.GetString("Page_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Page_Login {
            get {
                return ResourceManager.GetString("Page_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Page_Orders {
            get {
                return ResourceManager.GetString("Page_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Page_Privacy {
            get {
                return ResourceManager.GetString("Page_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Page_Products {
            get {
                return ResourceManager.GetString("Page_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Page_Profile {
            get {
                return ResourceManager.GetString("Page_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Page_Register {
            get {
                return ResourceManager.GetString("Page_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Page_Reports {
            get {
                return ResourceManager.GetString("Page_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Page_ResetPassword {
            get {
                return ResourceManager.GetString("Page_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Page_Settings {
            get {
                return ResourceManager.GetString("Page_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Page_Suppliers {
            get {
                return ResourceManager.GetString("Page_Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Page_Support {
            get {
                return ResourceManager.GetString("Page_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string Page_Terms {
            get {
                return ResourceManager.GetString("Page_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Page_Users {
            get {
                return ResourceManager.GetString("Page_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist.
        /// </summary>
        public static string Page_Wishlist {
            get {
                return ResourceManager.GetString("Page_Wishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string Sec_Activity {
            get {
                return ResourceManager.GetString("Sec_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string Sec_AdditionalInfo {
            get {
                return ResourceManager.GetString("Sec_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Information.
        /// </summary>
        public static string Sec_AddressInfo {
            get {
                return ResourceManager.GetString("Sec_AddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Information.
        /// </summary>
        public static string Sec_BillingInfo {
            get {
                return ResourceManager.GetString("Sec_BillingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string Sec_ContactInfo {
            get {
                return ResourceManager.GetString("Sec_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order History.
        /// </summary>
        public static string Sec_History {
            get {
                return ResourceManager.GetString("Sec_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Information.
        /// </summary>
        public static string Sec_LoginInfo {
            get {
                return ResourceManager.GetString("Sec_LoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        public static string Sec_Notifications {
            get {
                return ResourceManager.GetString("Sec_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        public static string Sec_OrderSummary {
            get {
                return ResourceManager.GetString("Sec_OrderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information.
        /// </summary>
        public static string Sec_PaymentInfo {
            get {
                return ResourceManager.GetString("Sec_PaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string Sec_PersonalInfo {
            get {
                return ResourceManager.GetString("Sec_PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Preferences.
        /// </summary>
        public static string Sec_Preferences {
            get {
                return ResourceManager.GetString("Sec_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details.
        /// </summary>
        public static string Sec_ProductDetails {
            get {
                return ResourceManager.GetString("Sec_ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Viewed.
        /// </summary>
        public static string Sec_RecentlyViewed {
            get {
                return ResourceManager.GetString("Sec_RecentlyViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended for You.
        /// </summary>
        public static string Sec_Recommended {
            get {
                return ResourceManager.GetString("Sec_Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Products.
        /// </summary>
        public static string Sec_RelatedProducts {
            get {
                return ResourceManager.GetString("Sec_RelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Reviews.
        /// </summary>
        public static string Sec_Reviews {
            get {
                return ResourceManager.GetString("Sec_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Settings.
        /// </summary>
        public static string Sec_Security {
            get {
                return ResourceManager.GetString("Sec_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Information.
        /// </summary>
        public static string Sec_ShippingInfo {
            get {
                return ResourceManager.GetString("Sec_ShippingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Sec_Statistics {
            get {
                return ResourceManager.GetString("Sec_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Tbl_Actions {
            get {
                return ResourceManager.GetString("Tbl_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Tbl_Address {
            get {
                return ResourceManager.GetString("Tbl_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Tbl_Category {
            get {
                return ResourceManager.GetString("Tbl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Tbl_City {
            get {
                return ResourceManager.GetString("Tbl_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Tbl_Country {
            get {
                return ResourceManager.GetString("Tbl_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Tbl_CreatedAt {
            get {
                return ResourceManager.GetString("Tbl_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Tbl_Customer {
            get {
                return ResourceManager.GetString("Tbl_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Tbl_Date {
            get {
                return ResourceManager.GetString("Tbl_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Tbl_Email {
            get {
                return ResourceManager.GetString("Tbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Tbl_ID {
            get {
                return ResourceManager.GetString("Tbl_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Tbl_Image {
            get {
                return ResourceManager.GetString("Tbl_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Tbl_Name {
            get {
                return ResourceManager.GetString("Tbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Tbl_OrderID {
            get {
                return ResourceManager.GetString("Tbl_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Tbl_Payment {
            get {
                return ResourceManager.GetString("Tbl_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Tbl_Phone {
            get {
                return ResourceManager.GetString("Tbl_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Tbl_Price {
            get {
                return ResourceManager.GetString("Tbl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Tbl_Product {
            get {
                return ResourceManager.GetString("Tbl_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Tbl_Quantity {
            get {
                return ResourceManager.GetString("Tbl_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Tbl_Role {
            get {
                return ResourceManager.GetString("Tbl_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string Tbl_Shipping {
            get {
                return ResourceManager.GetString("Tbl_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Tbl_Status {
            get {
                return ResourceManager.GetString("Tbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Tbl_Total {
            get {
                return ResourceManager.GetString("Tbl_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Tbl_Type {
            get {
                return ResourceManager.GetString("Tbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Tbl_UpdatedAt {
            get {
                return ResourceManager.GetString("Tbl_UpdatedAt", resourceCulture);
            }
        }
    }
}
