//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppResources.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppResources.Localization.Resources.ResValidation", typeof(ResValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. You do not have the required permissions.
        /// </summary>
        public static string Auth_AccessDenied {
            get {
                return ResourceManager.GetString("Auth_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked. Please try again after {0} minutes.
        /// </summary>
        public static string Auth_AccountLocked {
            get {
                return ResourceManager.GetString("Auth_AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not active. Please contact support.
        /// </summary>
        public static string Auth_AccountNotActive {
            get {
                return ResourceManager.GetString("Auth_AccountNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your email address before logging in.
        /// </summary>
        public static string Auth_EmailNotVerified {
            get {
                return ResourceManager.GetString("Auth_EmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        public static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to access this page.
        /// </summary>
        public static string Auth_LoginRequired {
            get {
                return ResourceManager.GetString("Auth_LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be different from current password.
        /// </summary>
        public static string Auth_NewPasswordSame {
            get {
                return ResourceManager.GetString("Auth_NewPasswordSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect.
        /// </summary>
        public static string Auth_OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("Auth_OldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must reset your password before continuing.
        /// </summary>
        public static string Auth_PasswordResetRequired {
            get {
                return ResourceManager.GetString("Auth_PasswordResetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your phone number before continuing.
        /// </summary>
        public static string Auth_PhoneNotVerified {
            get {
                return ResourceManager.GetString("Auth_PhoneNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please log in again.
        /// </summary>
        public static string Auth_TokenExpired {
            get {
                return ResourceManager.GetString("Auth_TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authentication token.
        /// </summary>
        public static string Auth_TokenInvalid {
            get {
                return ResourceManager.GetString("Auth_TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many failed attempts. Please try again after {0} minutes.
        /// </summary>
        public static string Auth_TooManyAttempts {
            get {
                return ResourceManager.GetString("Auth_TooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid two-factor authentication code.
        /// </summary>
        public static string Auth_TwoFactorInvalid {
            get {
                return ResourceManager.GetString("Auth_TwoFactorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication code is required.
        /// </summary>
        public static string Auth_TwoFactorRequired {
            get {
                return ResourceManager.GetString("Auth_TwoFactorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this action.
        /// </summary>
        public static string Auth_Unauthorized {
            get {
                return ResourceManager.GetString("Auth_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be different from current password.
        /// </summary>
        public static string Compare_CurrentNewPassword {
            get {
                return ResourceManager.GetString("Compare_CurrentNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email addresses do not match.
        /// </summary>
        public static string Compare_EmailMatch {
            get {
                return ResourceManager.GetString("Compare_EmailMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal to {1}.
        /// </summary>
        public static string Compare_Equal {
            get {
                return ResourceManager.GetString("Compare_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.
        /// </summary>
        public static string Compare_GreaterThan {
            get {
                return ResourceManager.GetString("Compare_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}.
        /// </summary>
        public static string Compare_GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("Compare_GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}.
        /// </summary>
        public static string Compare_LessThan {
            get {
                return ResourceManager.GetString("Compare_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}.
        /// </summary>
        public static string Compare_LessThanOrEqual {
            get {
                return ResourceManager.GetString("Compare_LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} do not match.
        /// </summary>
        public static string Compare_Match {
            get {
                return ResourceManager.GetString("Compare_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum value must be greater than minimum value.
        /// </summary>
        public static string Compare_MinMax {
            get {
                return ResourceManager.GetString("Compare_MinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be equal to {1}.
        /// </summary>
        public static string Compare_NotEqual {
            get {
                return ResourceManager.GetString("Compare_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string Compare_PasswordMatch {
            get {
                return ResourceManager.GetString("Compare_PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be after start date.
        /// </summary>
        public static string Compare_StartEndDate {
            get {
                return ResourceManager.GetString("Compare_StartEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected time slot is already booked.
        /// </summary>
        public static string Custom_BookingConflict {
            get {
                return ResourceManager.GetString("Custom_BookingConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon has expired.
        /// </summary>
        public static string Custom_CouponExpired {
            get {
                return ResourceManager.GetString("Custom_CouponExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid coupon code.
        /// </summary>
        public static string Custom_CouponInvalid {
            get {
                return ResourceManager.GetString("Custom_CouponInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon requires a minimum order of {0}.
        /// </summary>
        public static string Custom_CouponMinOrder {
            get {
                return ResourceManager.GetString("Custom_CouponMinOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon has already been used.
        /// </summary>
        public static string Custom_CouponUsed {
            get {
                return ResourceManager.GetString("Custom_CouponUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have an active order for this item.
        /// </summary>
        public static string Custom_DuplicateOrder {
            get {
                return ResourceManager.GetString("Custom_DuplicateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected {0} does not exist.
        /// </summary>
        public static string Custom_Exists {
            get {
                return ResourceManager.GetString("Custom_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient balance. Your balance: {0}.
        /// </summary>
        public static string Custom_InsufficientBalance {
            get {
                return ResourceManager.GetString("Custom_InsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient stock for {0}. Available: {1}.
        /// </summary>
        public static string Custom_InsufficientStock {
            get {
                return ResourceManager.GetString("Custom_InsufficientStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be performed on a {0} with status {1}.
        /// </summary>
        public static string Custom_InvalidOperation {
            get {
                return ResourceManager.GetString("Custom_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exceeds the allowed limit of {1}.
        /// </summary>
        public static string Custom_LimitExceeded {
            get {
                return ResourceManager.GetString("Custom_LimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum order amount is {0}.
        /// </summary>
        public static string Custom_MaximumOrder {
            get {
                return ResourceManager.GetString("Custom_MaximumOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot place more than {0} orders per day.
        /// </summary>
        public static string Custom_MaxOrders {
            get {
                return ResourceManager.GetString("Custom_MaxOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum order amount is {0}.
        /// </summary>
        public static string Custom_MinimumOrder {
            get {
                return ResourceManager.GetString("Custom_MinimumOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not allowed.
        /// </summary>
        public static string Custom_NotAllowed {
            get {
                return ResourceManager.GetString("Custom_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment processing failed. Please try again.
        /// </summary>
        public static string Custom_PaymentFailed {
            get {
                return ResourceManager.GetString("Custom_PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping is not available to the selected location.
        /// </summary>
        public static string Custom_ShippingRestriction {
            get {
                return ResourceManager.GetString("Custom_ShippingRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists.
        /// </summary>
        public static string Custom_Unique {
            get {
                return ResourceManager.GetString("Custom_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already registered.
        /// </summary>
        public static string Custom_UniqueEmail {
            get {
                return ResourceManager.GetString("Custom_UniqueEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone number is already registered.
        /// </summary>
        public static string Custom_UniquePhone {
            get {
                return ResourceManager.GetString("Custom_UniquePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already taken.
        /// </summary>
        public static string Custom_UniqueUsername {
            get {
                return ResourceManager.GetString("Custom_UniqueUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file appears to be corrupted.
        /// </summary>
        public static string File_Corrupted {
            get {
                return ResourceManager.GetString("File_Corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload up to {0} files.
        /// </summary>
        public static string File_Count {
            get {
                return ResourceManager.GetString("File_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot upload more than {0} files.
        /// </summary>
        public static string File_CountExceeded {
            get {
                return ResourceManager.GetString("File_CountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid document (pdf, doc, docx, etc).
        /// </summary>
        public static string File_Document {
            get {
                return ResourceManager.GetString("File_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file is empty.
        /// </summary>
        public static string File_Empty {
            get {
                return ResourceManager.GetString("File_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid image file (jpg, png, gif, etc).
        /// </summary>
        public static string File_Image {
            get {
                return ResourceManager.GetString("File_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image dimensions must be between {0}x{1} and {2}x{3} pixels.
        /// </summary>
        public static string File_ImageDimensions {
            get {
                return ResourceManager.GetString("File_ImageDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image must not exceed {0}x{1} pixels.
        /// </summary>
        public static string File_ImageMaxDimensions {
            get {
                return ResourceManager.GetString("File_ImageMaxDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image must be at least {0}x{1} pixels.
        /// </summary>
        public static string File_ImageMinDimensions {
            get {
                return ResourceManager.GetString("File_ImageMinDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image must have aspect ratio {0}:{1}.
        /// </summary>
        public static string File_ImageRatio {
            get {
                return ResourceManager.GetString("File_ImageRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image must be square (width equals height).
        /// </summary>
        public static string File_ImageSquare {
            get {
                return ResourceManager.GetString("File_ImageSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file to upload.
        /// </summary>
        public static string File_Required {
            get {
                return ResourceManager.GetString("File_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size cannot exceed {0} MB.
        /// </summary>
        public static string File_Size {
            get {
                return ResourceManager.GetString("File_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file exceeds the maximum allowed size of {0} MB.
        /// </summary>
        public static string File_SizeExceeded {
            get {
                return ResourceManager.GetString("File_SizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} files are allowed.
        /// </summary>
        public static string File_Type {
            get {
                return ResourceManager.GetString("File_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type. Allowed types: {0}.
        /// </summary>
        public static string File_TypeInvalid {
            get {
                return ResourceManager.GetString("File_TypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only letters and numbers are allowed.
        /// </summary>
        public static string Format_AlphaNumeric {
            get {
                return ResourceManager.GetString("Format_AlphaNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only contain letters and numbers.
        /// </summary>
        public static string Format_AlphaNumericWithField {
            get {
                return ResourceManager.GetString("Format_AlphaNumericWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid credit card number.
        /// </summary>
        public static string Format_CreditCard {
            get {
                return ResourceManager.GetString("Format_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid credit card number.
        /// </summary>
        public static string Format_CreditCardWithField {
            get {
                return ResourceManager.GetString("Format_CreditCardWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date.
        /// </summary>
        public static string Format_Date {
            get {
                return ResourceManager.GetString("Format_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date and time.
        /// </summary>
        public static string Format_DateTime {
            get {
                return ResourceManager.GetString("Format_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid date and time.
        /// </summary>
        public static string Format_DateTimeWithField {
            get {
                return ResourceManager.GetString("Format_DateTimeWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid date.
        /// </summary>
        public static string Format_DateWithField {
            get {
                return ResourceManager.GetString("Format_DateWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid decimal number.
        /// </summary>
        public static string Format_Decimal {
            get {
                return ResourceManager.GetString("Format_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid decimal number.
        /// </summary>
        public static string Format_DecimalWithField {
            get {
                return ResourceManager.GetString("Format_DecimalWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string Format_Email {
            get {
                return ResourceManager.GetString("Format_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid email address.
        /// </summary>
        public static string Format_EmailWithField {
            get {
                return ResourceManager.GetString("Format_EmailWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid hex color code (e.g., #FF0000).
        /// </summary>
        public static string Format_HexColor {
            get {
                return ResourceManager.GetString("Format_HexColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a whole number.
        /// </summary>
        public static string Format_Integer {
            get {
                return ResourceManager.GetString("Format_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a whole number.
        /// </summary>
        public static string Format_IntegerWithField {
            get {
                return ResourceManager.GetString("Format_IntegerWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid IP address.
        /// </summary>
        public static string Format_IPAddress {
            get {
                return ResourceManager.GetString("Format_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only letters are allowed.
        /// </summary>
        public static string Format_LettersOnly {
            get {
                return ResourceManager.GetString("Format_LettersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only contain letters.
        /// </summary>
        public static string Format_LettersOnlyWithField {
            get {
                return ResourceManager.GetString("Format_LettersOnlyWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid mobile number.
        /// </summary>
        public static string Format_Mobile {
            get {
                return ResourceManager.GetString("Format_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special characters are not allowed.
        /// </summary>
        public static string Format_NoSpecialChars {
            get {
                return ResourceManager.GetString("Format_NoSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot contain special characters.
        /// </summary>
        public static string Format_NoSpecialCharsWithField {
            get {
                return ResourceManager.GetString("Format_NoSpecialCharsWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number.
        /// </summary>
        public static string Format_Number {
            get {
                return ResourceManager.GetString("Format_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numbers are allowed.
        /// </summary>
        public static string Format_NumbersOnly {
            get {
                return ResourceManager.GetString("Format_NumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only contain numbers.
        /// </summary>
        public static string Format_NumbersOnlyWithField {
            get {
                return ResourceManager.GetString("Format_NumbersOnlyWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid number.
        /// </summary>
        public static string Format_NumberWithField {
            get {
                return ResourceManager.GetString("Format_NumberWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number.
        /// </summary>
        public static string Format_Phone {
            get {
                return ResourceManager.GetString("Format_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid phone number.
        /// </summary>
        public static string Format_PhoneWithField {
            get {
                return ResourceManager.GetString("Format_PhoneWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid postal code.
        /// </summary>
        public static string Format_PostalCode {
            get {
                return ResourceManager.GetString("Format_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid postal code.
        /// </summary>
        public static string Format_PostalCodeWithField {
            get {
                return ResourceManager.GetString("Format_PostalCodeWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character.
        /// </summary>
        public static string Format_StrongPassword {
            get {
                return ResourceManager.GetString("Format_StrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid time.
        /// </summary>
        public static string Format_Time {
            get {
                return ResourceManager.GetString("Format_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid time.
        /// </summary>
        public static string Format_TimeWithField {
            get {
                return ResourceManager.GetString("Format_TimeWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL.
        /// </summary>
        public static string Format_Url {
            get {
                return ResourceManager.GetString("Format_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid URL.
        /// </summary>
        public static string Format_UrlWithField {
            get {
                return ResourceManager.GetString("Format_UrlWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only contain letters, numbers, and underscores.
        /// </summary>
        public static string Format_Username {
            get {
                return ResourceManager.GetString("Format_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be exactly {1} characters.
        /// </summary>
        public static string Length_Exact {
            get {
                return ResourceManager.GetString("Length_Exact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters.
        /// </summary>
        public static string Length_Max {
            get {
                return ResourceManager.GetString("Length_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum {0} characters.
        /// </summary>
        public static string Length_MaxSimple {
            get {
                return ResourceManager.GetString("Length_MaxSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1} characters.
        /// </summary>
        public static string Length_Min {
            get {
                return ResourceManager.GetString("Length_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum {0} characters.
        /// </summary>
        public static string Length_MinSimple {
            get {
                return ResourceManager.GetString("Length_MinSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2} characters.
        /// </summary>
        public static string Length_Range {
            get {
                return ResourceManager.GetString("Length_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is too long.
        /// </summary>
        public static string Length_TooLong {
            get {
                return ResourceManager.GetString("Length_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is too short.
        /// </summary>
        public static string Length_TooShort {
            get {
                return ResourceManager.GetString("Length_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be at least {0} years old.
        /// </summary>
        public static string Range_Age {
            get {
                return ResourceManager.GetString("Range_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}.
        /// </summary>
        public static string Range_Date {
            get {
                return ResourceManager.GetString("Range_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a future date.
        /// </summary>
        public static string Range_Future {
            get {
                return ResourceManager.GetString("Range_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not exceed {1}.
        /// </summary>
        public static string Range_Max {
            get {
                return ResourceManager.GetString("Range_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1}.
        /// </summary>
        public static string Range_Min {
            get {
                return ResourceManager.GetString("Range_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a negative number.
        /// </summary>
        public static string Range_Negative {
            get {
                return ResourceManager.GetString("Range_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be zero.
        /// </summary>
        public static string Range_NonZero {
            get {
                return ResourceManager.GetString("Range_NonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be a future date.
        /// </summary>
        public static string Range_NotFuture {
            get {
                return ResourceManager.GetString("Range_NotFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be a past date.
        /// </summary>
        public static string Range_NotPast {
            get {
                return ResourceManager.GetString("Range_NotPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}.
        /// </summary>
        public static string Range_Number {
            get {
                return ResourceManager.GetString("Range_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a past date.
        /// </summary>
        public static string Range_Past {
            get {
                return ResourceManager.GetString("Range_Past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a positive number.
        /// </summary>
        public static string Range_Positive {
            get {
                return ResourceManager.GetString("Range_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be today or a future date.
        /// </summary>
        public static string Range_TodayOrFuture {
            get {
                return ResourceManager.GetString("Range_TodayOrFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be today or a past date.
        /// </summary>
        public static string Range_TodayOrPast {
            get {
                return ResourceManager.GetString("Range_TodayOrPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to the terms and conditions.
        /// </summary>
        public static string Req_Agree {
            get {
                return ResourceManager.GetString("Req_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must check this box to continue.
        /// </summary>
        public static string Req_Check {
            get {
                return ResourceManager.GetString("Req_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string Req_Field {
            get {
                return ResourceManager.GetString("Req_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a {0}.
        /// </summary>
        public static string Req_Select {
            get {
                return ResourceManager.GetString("Req_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string Req_Simple {
            get {
                return ResourceManager.GetString("Req_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a {0}.
        /// </summary>
        public static string Req_Upload {
            get {
                return ResourceManager.GetString("Req_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists.
        /// </summary>
        public static string Val_AlreadyExists {
            get {
                return ResourceManager.GetString("Val_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty.
        /// </summary>
        public static string Val_CannotBeEmpty {
            get {
                return ResourceManager.GetString("Val_CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be negative.
        /// </summary>
        public static string Val_CannotBeNegative {
            get {
                return ResourceManager.GetString("Val_CannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null.
        /// </summary>
        public static string Val_CannotBeNull {
            get {
                return ResourceManager.GetString("Val_CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be zero.
        /// </summary>
        public static string Val_CannotBeZero {
            get {
                return ResourceManager.GetString("Val_CannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid.
        /// </summary>
        public static string Val_Invalid {
            get {
                return ResourceManager.GetString("Val_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        public static string Val_InvalidFormat {
            get {
                return ResourceManager.GetString("Val_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string Val_InvalidInput {
            get {
                return ResourceManager.GetString("Val_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection.
        /// </summary>
        public static string Val_InvalidSelection {
            get {
                return ResourceManager.GetString("Val_InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        public static string Val_InvalidValue {
            get {
                return ResourceManager.GetString("Val_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must match {1}.
        /// </summary>
        public static string Val_MustMatch {
            get {
                return ResourceManager.GetString("Val_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found.
        /// </summary>
        public static string Val_NotFound {
            get {
                return ResourceManager.GetString("Val_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is out of range.
        /// </summary>
        public static string Val_OutOfRange {
            get {
                return ResourceManager.GetString("Val_OutOfRange", resourceCulture);
            }
        }
    }
}
